# Generated by Django 4.1.2 on 2022-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("int", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
                (
                    "nature_choices",
                    models.CharField(
                        choices=[("Entrada", "Add"), ("Saida", "Subtract")],
                        max_length=20,
                    ),
                ),
                (
                    "sinal_choices",
                    models.CharField(
                        choices=[("+", "Add"), ("-", "Subtract")], max_length=20
                    ),
                ),
            ],
        ),
    ]
